// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7T9_JPrTR1n6UdiFID850TXsVBHAeqI',
    appId: '1:762006944068:web:bb0eb307b9c5316291bf11',
    messagingSenderId: '762006944068',
    projectId: 'flutter-project-4226b',
    authDomain: 'flutter-project-4226b.firebaseapp.com',
    storageBucket: 'flutter-project-4226b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkIlWLnHTBNnHlpJsOVvAtpek50Mc2G-0',
    appId: '1:762006944068:android:44b534aa7159989491bf11',
    messagingSenderId: '762006944068',
    projectId: 'flutter-project-4226b',
    storageBucket: 'flutter-project-4226b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9922oTTWYPeLoafwKbTp-RIwpt1-sxk',
    appId: '1:762006944068:ios:a03209ae91fa5d3a91bf11',
    messagingSenderId: '762006944068',
    projectId: 'flutter-project-4226b',
    storageBucket: 'flutter-project-4226b.appspot.com',
    iosBundleId: 'com.example.assignment6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN9922oTTWYPeLoafwKbTp-RIwpt1-sxk',
    appId: '1:762006944068:ios:a03209ae91fa5d3a91bf11',
    messagingSenderId: '762006944068',
    projectId: 'flutter-project-4226b',
    storageBucket: 'flutter-project-4226b.appspot.com',
    iosBundleId: 'com.example.assignment6',
  );
}
